# Generated by Django 3.1.3 on 2020-11-18 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('NIP', models.CharField(max_length=20, unique=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('role', models.CharField(choices=[('AD', 'Administration'), ('DR', 'Driver')], max_length=2)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('birth_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('billing_address', models.TextField(blank=True, max_length=200, null=True)),
                ('availability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('qualifications', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=40)),
                ('production_date', models.DateField(blank=True, default=django.utils.datetime_safe.date.today, null=True)),
                ('company_registration_date', models.DateField(blank=True, default=django.utils.datetime_safe.date.today, null=True)),
                ('vin', models.CharField(max_length=40)),
                ('reg_number', models.CharField(max_length=40)),
                ('availability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('odometer', models.IntegerField(blank=True, null=True)),
                ('service_interval', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('LOR', 'Lorry'), ('TRA', 'Tractor'), ('CIS', 'Cistern'), ('CON', 'Container')], max_length=3)),
                ('max_load', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('route_type', models.CharField(choices=[('KM', 'Distance'), ('TN', 'Weight')], max_length=2)),
                ('load_type', models.CharField(choices=[('MS', 'Dry mass'), ('LI', 'Liquid'), ('CO', 'Container')], max_length=2)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed')], max_length=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('truck', models.ManyToManyField(to='core.Truck')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('fuel_consumed', models.IntegerField(blank=True, null=True)),
                ('start', models.CharField(blank=True, max_length=40, null=True)),
                ('end', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.truck')),
            ],
        ),
    ]
