# Generated by Django 3.1.3 on 2020-11-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trucks'),
        ),
    ]
