# Generated by Django 3.1.3 on 2020-11-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_truck_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroute',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='dailyroute',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.order'),
        ),
        migrations.AlterField(
            model_name='dailyroute',
            name='truck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.truck'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='truck.jpg', null=True, upload_to='employees'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='photo',
            field=models.ImageField(blank=True, default='truck.jpg', null=True, upload_to='trucks'),
        ),
    ]
